CREATE DATABASE IF NOT EXISTS `MOVIE_LISTS`; 
USE MOVIE_LISTS;

CREATE TABLE `MOVIES` (
  `movie_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(42),
  `score` INT,
  `review` VARCHAR(254),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `USERS` (
  `id` VARCHAR(42),
  `first_name` VARCHAR(42),
  `last_name` VARCHAR(42),
  `pseudo` VARCHAR(42),
  `password` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `WATCH_LISTS` (
  `id` VARCHAR(42),
  `name` VARCHAR(42),
  `description` VARCHAR(42),
  `color` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `MOVIES` ADD FOREIGN KEY (`id_1`) REFERENCES `WATCH_LISTS` (`id`);
ALTER TABLE `WATCH_LISTS` ADD FOREIGN KEY (`id_1`) REFERENCES `USERS` (`id`);
